trigger:
- master

name: 1.10.$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BQC.ForceNewBaseline: false

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build and Test

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8'
      inputs:
        version: 8.0.x
        includePreviewVersions: false

    - task: NuGetToolInstaller@1

    - task: DotNetCoreCLI@2
      displayName: 'Restore nuget packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '-c Release /p:NoWarn=0618'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'
        arguments: '--collect "Code coverage" --configuration $(buildConfiguration) --filter "Category!=Database"'

    #- task: BuildQualityChecks@8
    #  displayName: 'Build Quality Checks'
    #  inputs:
    #    checkWarnings: true
    #    warningFailOption: 'build'
    #    allowWarningVariance: true
    #    warningVariance: '1'
    #    checkCoverage: true
    #    coverageFailOption: 'build'
    #    coverageType: 'blocks'
    #    allowCoverageVariance: true
    #    coverageVariance: '1'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Toolkit'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Toolkit.csproj'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Toolkit.Standard'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Toolkit.Standard.csproj'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Test.Toolkit'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Test.Toolkit.csproj'
        versioningScheme: 'byBuildNumber'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Tharga.Toolkit.TimerJob'
      inputs:
        command: 'pack'
        packagesToPack: '**/Tharga.Toolkit.TimerJob.csproj'
        versioningScheme: 'byBuildNumber'

    #- task: DotNetCoreCLI@2
    #  displayName: 'Push nuget packages locally'
    #  inputs:
    #    command: 'push'
    #    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    #    nuGetFeedType: 'internal'
    #    publishVstsFeed: 'df4b267e-c55c-4a36-8fe3-8e98d5d8dbbb/5cea672d-cb79-44f6-beb8-2eaba59e670d'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Release
  displayName: Release
  dependsOn: Build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Release
    displayName: Release

    steps:
    - download: current
      artifact: drop
    - checkout: self
      persistCredentials: true

    - task: NuGetCommand@2
      displayName: 'Push nuget packages to nuget.org'
      inputs:
        command: 'push'
        packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget.org'

    - script: |
         git tag $(Build.BuildNumber)
         git push origin $(Build.BuildNumber)
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Tag
